language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python tests.py
deploy:
  - provider: script
    script: ./deploy-production.sh
    skip_cleanup: true
    on:
      branch: master
notifications:
  webhooks:
    - http://397f93be.ngrok.io/travis
